services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 public/index.php
    networks:
      - my-network
networks:
  my-network:
    external: true
