services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    command: php -S 0.0.0.0:8002 public/index.php
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
