FROM php:7.4-alpine3.15

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

COPY ./BookstoreApiGateway /src
WORKDIR /src

RUN docker-php-ext-install sockets

RUN composer update

WORKDIR /src/database

RUN touch database.sqlite

WORKDIR /src

RUN php artisan migrate && \
php artisan passport:install

# run the php server service
# move this command to -> docker-compose.yml
# CMD php -S 0.0.0.0:8080 public/index.php