services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8006:8006
    command: php -S 0.0.0.0:8006 index.php
    networks:
      - my-network
networks:
  my-network:
    external: true
